### ISSUE TITLE
(SOLVED) Error: Timestamp for this request was 1000ms ahead of the server's time.

### ISSUE THREAD

**Issue by Chazzr** [austinyearlykim/wolf#1]
### CONDITIONS
1. Windows

### STEPS
1.  Launch Git Bash
2.  Navigate to cloned WOLF repo directory
3.  Run 'npm start'

### RESULT
Console response will result in the following error:
`
Error: Timestamp for this request was 1000ms ahead of the server's time.
    at E:\NodeProjects\wolf\node_modules\binance-api-node\dist\http.js:47:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
`

**Comment by Chazzr** [comment]
Ive only seen this issue on Windows so far. But good news, I discovered the fix for this. On windows your Internet time settings are set to `time.windows.com`. You need to change it to `time.nist.gov`.  You can find this setting via **_Control Panel > Date & Time > Internet Time_**.

Screenshot for your viewing pleasure:
![changeinternettimesettingsnist](https://user-images.githubusercontent.com/29960834/34978831-5df8c59c-fa54-11e7-8d06-494b83a523f0.PNG)

**Comment by austinyearlykim** [comment]
Looks like this is the problem/solution for all Windows users.  I'll be sure to add this to the README.  Thank you @Chazzr !
