### ISSUE TITLE
fill or kill

### ISSUE THREAD

**Issue by pipinoloco** [austinyearlykim/wolf#12]
another cool feature could be fill or kill, example, fill at market price, if the order was partially filled sell the order at 0.1% above the purchased price.
if the limit order is not filled, cancel and buy at -1% the market price example.

**Comment by austinyearlykim** [comment]
Cool feature, but right now it's a little too out of scope of what I want wolf to be.  I'm trying to have wolf be near risk-free, at least for the few first major versions.  Excellent idea @pipinoloco, it's just a little ahead of schedule right now.  Buying/selling at market price seems like v3 or v4 when WOLF get's smarter about past transactions and etc.
