### ISSUE TITLE
budget in confi

### ISSUE THREAD

**Issue by pipinoloco** [austinyearlykim/wolf#13]
i think it would be easy to put for example in config a budget of 0.5 ether and the bot calculates how much to buy and sell, the basic config is good but harder to calculate.

**Comment by austinyearlykim** [comment]
The budget at least for now is the budget *per transaction*.  Maybe you can reply with a config that you can easier understand and I'll look to see if I can change any of it in an upcoming release

**Comment by pipinoloco** [comment]
i have seen in another bot some sort of leveraged budget, it means it won-t have a fixed budget in ETH for example if not 100% of the other pair, 80% of the other pair etc. As you are not selling 100% of the "other" pair, example you bought 100 TRX but TRX rised a lot, you can sell only 50% and hold 50%, not selling 100% on each trade. Also if the price drops a lot you can put a larger order, because you have a market opportunity, with a fixed budget you can lose those opportnities, as you are buying and selling with a budget of 0.50 ETH and if ETH drops a lot compared to BTC you are not winning more money than buying "more" TRX when cheap and selling less when TRX is expensive.
