### ISSUE TITLE
close all open trades by wolf when program exits or crash

### ISSUE THREAD

**Issue by pipinoloco** [austinyearlykim/wolf#14]
can the program cancel open orders when crash or close

**Comment by austinyearlykim** [comment]
I've wanted to do this, and it definitely is possible.  Consider it part of v2.1.0; releasing sometime next week.

**Comment by austinyearlykim** [comment]
Done.

https://github.com/austinyearlykim/wolf/commit/253d167fdbac857230ef2c644e8e483cc1ac62a0
