### ISSUE TITLE
Rolling budget enhancement

### ISSUE THREAD

**Issue by sasasavic82** [austinyearlykim/wolf#2]
Thought about compounding budget?

i.e. = starting budget $100 ... after say, 10% profit percentage, instead of $100 order, you place a $110 order? When you make $121, rinse and repeat. :)

**Comment by austinyearlykim** [comment]
Hi @sasasavic82,

YES.  LOVE IT.  After refactoring and modularizing the codebase I'll be adding "strategies" that we can run via `npm start long` or `npm start short` or something of that nature.  You can maybe tell that your compounding budget idea is great in a bullish run but would have a bit of trouble executing when theres a downtrend.  

WOLF will only get smarter from here.  Super excited that I have users on the 2nd day already of it being released.
