### ISSUE TITLE
Auto Set Maximum Budget Available to Allow Compounding

### ISSUE THREAD

**Issue by newgithubacc1v** [austinyearlykim/wolf#20]
Only if possible, is it possible to add an auto set feature for the maximum available budget to effectively allow compounding of budget?

**Comment by austinyearlykim** [comment]
Hi @newgithubacc1v,
I'm going to get some time to work on WOLF this weekend, look out for a update for wolf v3.2.0 soon

**Comment by newgithubacc1v** [comment]
@austinyearlykim Great! Looking forward to the feature.

**Comment by austinyearlykim** [comment]
https://github.com/austinyearlykim/wolf/commit/ed04e6fdfb5c15392c18076ff1012db89fe9aef5

Please update your repo to v3.2.0 and view the README.md for the COMPOUND feature in the .env section.  You need to add the option to your .env and have it equal to true.
