### ISSUE TITLE
User receives a TYPE ERROR after multiple successful trades

### ISSUE THREAD

**Issue by Chazzr** [austinyearlykim/wolf#3]
Ive run into this error multiple times tonight. It appears after multiple successful trades. I have plenty of budget so I dont believe it is a problem with insufficient funds. Perhaps the callstack below will be helpful. 

I dont have repro steps at this point but I will update this issue once I do.

### Callstack

`TypeError: Cannot read property 'price' of null
    at Timeout.setInterval [as _onTimeout] (E:\nodeprojects\wolf\index.js:77:50)
    at ontimeout (timers.js:458:11)
    at tryOnTimeout (timers.js:296:5)
    at Timer.listOnTimeout (timers.js:259:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wolf@1.0.0 start: `npm test && node .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wolf@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by austinyearlykim** [comment]
Hi @Chazzr,

Thanks for being active in exposing issues!  This error is from a small race condition.  Now that I've gotten feedback from several people and after iterating on v1, I'll be refactoring WOLF to be a bit more synchronous in nature.  Look out for updates, you've been a great help
