### ISSUE TITLE
test fails because of ticker..

### ISSUE THREAD

**Issue by BatmanPDX** [austinyearlykim/wolf#30]
when I try to run the bot, it fails with this message:

 2) Ticker
       should be able to execute array of callbacks:

      Uncaught AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true

      at Timeout.setTimeout [as _onTimeout] (test\ticker.js:49:21)

  3) Ticker
       should be able access Ticker meta data:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

npm ERR! Test failed.  See above for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wolf@3.3.0 start: `npm test && node .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wolf@3.3.0 start script.

**Comment by BatmanPDX** [comment]
nevermind I fixed it. sorry

**Comment by austinyearlykim** [comment]
all good! thanks @BatmanPDX !
