### ISSUE TITLE
Not enough TRX balance in Binance wallet

### ISSUE THREAD

**Issue by pitxels** [austinyearlykim/wolf#38]
Hi, I have a problem, I have this on my .env file:

```
BUDGET=0.01785347
PROFIT_PERCENTAGE=1.1
TARGET_ASSET=TRX
BASE_ASSET=BTC
```
And I am positive I have that BTC balance on Binance. When I run the test I get:
`not enough TRX balance in Binance wallet to use W.O.L.F with your budget.  Balance: 0.00000000 Budget: 0.01785347`

Why is it checking my TRX balance? when I am going to use BTC to buy It....

**Comment by austinyearlykim** [comment]
Fixed: 

https://github.com/austinyearlykim/wolf/commit/50cb05ee4a2b336195c58bb433be107846868fe0

woohoo
