### ISSUE TITLE
Stop Loss not triggered

### ISSUE THREAD

**Issue by pitxels** [austinyearlykim/wolf#41]
Hi, I am testing stop-loss, I started with a 0.5 value but it was not working, then I realised that I have to use whole numbers so I set that to 1.

However in my current trade I have lost 2.2 % and there was not any order created to stop it.

My settings:

```
BUDGET=0.0025
PROFIT_PERCENTAGE=2
TARGET_ASSET=ZEC
BASE_ASSET=BTC
STOP_LIMIT_PERCENTAGE=1
PROFIT_LOCK_PERCENTAGE=false
COMPOUND=true 
```

**Comment by austinyearlykim** [comment]
Hi @pitxels,

Let me get back to you on this later tonight, thank you for the detailed bug report.

**Comment by BatmanPDX** [comment]
Yea, @austinyearlykim I just quick test on it, it doesn't trigger.

**Comment by austinyearlykim** [comment]
I fixed a bug and released a patch version tonight, getting late, but for any eyes that are on this issue...

https://github.com/austinyearlykim/wolf/blob/master/modules/Wolf.js#L94

...is the line responsible for the stop loss trigger.  Hmmmmmm... might be a good debugging session with some morning coffee for me.  Cheers!

**Comment by austinyearlykim** [comment]
https://github.com/austinyearlykim/wolf/pull/56/files

view PR notes for more info! will merge in a bit.

**Comment by austinyearlykim** [comment]
merged, closing please oppen new bug ticket if issues persist! <3
