### ISSUE TITLE
Purchase Error message

### ISSUE THREAD

**Issue by BatmanPDX** [austinyearlykim/wolf#43]
I turned off my ip blocker to see if maybe that was interfering and I also refreshed my nettime sync. That seem to fix the ticker problem. Ran a test 3 times, and all three passed the test. but now it's giving a purchase error:
__________________________________________________
 Ticker
    √ should be able construct Ticker
    √ should be able to initialize Ticker (1268ms)
    √ should be able to execute array of callbacks (4000ms)
    √ should be able access Ticker meta data

  20 passing (10s)

Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 0
W.O.L.F is hunting...
Calculating quantity...
Quantity Calculated:  110.000
PURCHASE ERROR:  Error: Filter failure: MIN_NOTIONAL
    at C:\wolf\node_modules\binance-api-node\dist\http.js:47:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 0
Cancelling 0 open orders created by W.O.L.F
Cancelled 0 opened orders created by W.O.L.F

**Comment by austinyearlykim** [comment]
`MIN_NOTIONAL` is an error from binance because the value of the amount you're trying to purchase is too low.  Raising your budget, will fix this issue.  There probably should be a mocha test case that checks for this.  I'll get to this after the dust settles :)
