### ISSUE TITLE
Sell issued but no rebuy , and error.

### ISSUE THREAD

**Issue by BatmanPDX** [austinyearlykim/wolf#44]
the bot completed a buy and sell, but it didn't create a new buy. It just keeps showing me this. I do have enough money to complete the next order. even if I didn't, the sell order should've covered it.

Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  1
Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  1
Consumed queue. Orders in queue: 0
Selling... TRXBTC
Consuming queue... Orders in queue: 1
SOLD: 110.00000000TRXBTC @  0.00000912
Compounding... 2.0000000000001503e-8
W.O.L.F is hunting...
Calculating quantity...
Quantity Calculated:  109.000
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 0
PURCHASE ERROR:  Error: Filter failure: MIN_NOTIONAL
    at C:\wolf\node_modules\binance-api-node\dist\http.js:47:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  0

Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 0

**Comment by austinyearlykim** [comment]
working on a fix for this at the moment <3

https://github.com/austinyearlykim/wolf/issues/28
