### ISSUE TITLE
MIN_NOTIONAL error?

### ISSUE THREAD

**Issue by BatmanPDX** [austinyearlykim/wolf#45]
I have .004 in my account, and I set the bot to use .001 but it gives me this error:

20 passing (10s)

Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  0
Consumed queue. Orders in queue: 0
W.O.L.F is hunting...
Calculating quantity...
Quantity Calculated:  110.000
PURCHASE ERROR:  Error: Filter failure: MIN_NOTIONAL
    at C:\wolf\node_modules\binance-api-node\dist\http.js:47:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  0

**Comment by austinyearlykim** [comment]
`MIN_NOTIONAL` error is from the binance api, not necessarily a WOLF problem.

https://www.reddit.com/r/binance/comments/74ocol/api_errorfilter_failure_min_notional/

Raising your BUDGET should fix the problem if this is happening for your initial purchase...

If `MIN_NOTIONAL` shows up again, then it's W.O.L.F problem :) 

As per: 
https://github.com/austinyearlykim/wolf/issues/28
https://github.com/austinyearlykim/wolf/issues/44

**Comment by BatmanPDX** [comment]
ok I'll try it out

**Comment by austinyearlykim** [comment]
woo hoo!
