### ISSUE TITLE
Extra trading pairs.

### ISSUE THREAD

**Issue by BatmanPDX** [austinyearlykim/wolf#47]
Hey @austinyearlykim It would be awesome if we could do more than one trade pair at a time.

something like: 
TARGET_ASSET1=TRX
BASE_ASSET1=BTC

TARGET_ASSET2=TRX
BASE_ASSET2=BTC

TARGET_ASSET3=TRX
BASE_ASSET3=BTC

**Comment by austinyearlykim** [comment]
good input!, might be better to put this suggestion into: https://github.com/austinyearlykim/wolf/issues/11
