### ISSUE TITLE
Account has insufficient balance for requested action.

### ISSUE THREAD

**Issue by BatmanPDX** [austinyearlykim/wolf#49]
the bot did a successful buy and sell order the first time. Then the second time around, it does a buy but it says this when it tries to sell:

Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  1
Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  1
Consumed queue. Orders in queue: 0
SELL ERROR:  Account has insufficient balance for requested action.

kinda strange to see that on a sell order. Maybe it's thinking there are more shares available than there is. Maybe miss calculation on including fees... Just a guess.

**Comment by austinyearlykim** [comment]
`Account has insufficient balance for requested action.`

Is an error from the binance API.  

Do you have enough balance to buy/sell it twice?  Your assets that you buy/sell through W.O.L.F have to "settle", or become "free".  Maybe having around 3x of your BASE_ASSET and TARGET_ASSET available would help as your first trade needs time to free up funds even if you've made a profit.

**Comment by BatmanPDX** [comment]
Ok, I've give it a try later. thnx

**Comment by BatmanPDX** [comment]
Nope, it wasn't that. I just did a test with only .0015 and I have a balance of .008. It still gave me a SELL ERROR:  Account has insufficient balance for requested action.

**Comment by austinyearlykim** [comment]
interesting..

Post your .env variables?

DON'T POST YOUR BINANCE KEYS

DON'T POST YOUR BINANCE KEYS
DON'T POST YOUR BINANCE KEYS
DON'T POST YOUR BINANCE KEYS
DON'T POST YOUR BINANCE KEYS

DON'T POST YOUR BINANCE KEYS

DON'T POST YOUR BINANCE KEYS

DON'T POST YOUR BINANCE KEYS
DON'T POST YOUR BINANCE KEYS
DON'T POST YOUR BINANCE KEYS

**Comment by BatmanPDX** [comment]
BUDGET=0.0025
PROFIT_PERCENTAGE=0.1

#if your desired trading pair is ADAETH, below is the correct way to configure W.O.L.F
TARGET_ASSET=TRX
BASE_ASSET=BTC






#<-----------------optional----------------->

#this is a bit complex please view README.md for more info; pick one. not both.
STOP_LOSS_PERCENTAGE=0.09

#this is a bit complex please view README.md for more info
PROFIT_LOCK_PERCENTAGE=false

#if true, gains will get compounded into the following trade
COMPOUND=true

**Comment by BatmanPDX** [comment]
so strange, I've been running it for about 30 mins now with no problems. don't know what it could've been.

**Comment by austinyearlykim** [comment]
if the problem arises let's make another ticket!
