### ISSUE TITLE
unknown attribute price

### ISSUE THREAD

**Issue by sasasavic82** [austinyearlykim/wolf#5]
yo!!! :) I'll keep digging away... i like the bot.

issue:

Your fudInterval executes after reset() is called. there's a time conflict causing the confirmedPurchase.price to fail because you nullfied it

**Comment by austinyearlykim** [comment]
Someone else noticed this too :)

https://github.com/austinyearlykim/wolf/issues/3

v1.1.0 will fix this.  ETA early next week, maybe sunday!
