### ISSUE TITLE
bot seems to pause/timeout after a while

### ISSUE THREAD

**Issue by BatmanPDX** [austinyearlykim/wolf#55]
Ran the bot successfully for an hr or two. It was constantly outputting and then it just stopped outputting and paused on the last row for 30mins before I canceled it.:
Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  1
Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  1
Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  1
Consumed queue. Orders in queue: 0
Consuming queue... Orders in queue: 0
Watching watchlist... Orders in watchlist:  1
Consumed queue. Orders in queue: 0

maybe a memory issue?
Or maybe it's just Git Bash timing out.

**Comment by austinyearlykim** [comment]
not entirely sure yet. this will be more visible with incoming changes to the logging system too!

**Comment by BatmanPDX** [comment]
I switched to powershell and it has been running for 8 hrs without any problem. I think it was a memory problem with Bash

**Comment by austinyearlykim** [comment]
love to hear this!

thanks for the update @BatmanPDX
