### ISSUE TITLE
Sell error bug: account has insufficient balance for requested action

### ISSUE THREAD

**Issue by awalch23** [austinyearlykim/wolf#67]
Hello,

Queue: 0 Watchlist: 1 [ALARM]::: Price dipped below PROFIT_LOCK_PERCENTAGE while in paranoid mode. Selling.
Queue: 0 Watchlist: 1SELL ERROR:  Account has insufficient balance for requested action.

I had 155 units, Binance took .15 of them as transaction fee, leaving me with a whole number of 154 left. I believe Wolf was trying to sell 155 units or 154.85 units. When I went into Binance app, I was only able to manually sell 154 of the 155 Wolf purchased. I think this has to do with rounding. Is there a way to decrement the number of units attempted to be sold if that sell error occurs so the sale still happens?

Thanks!
Alex

**Comment by austinyearlykim** [comment]
Great find @awalch23,

I'll be sure to include a fix for this in the next release!

**Comment by awalch23** [comment]
Thanks! This is a great app and well written JavaScript.

**Comment by austinyearlykim** [comment]
Hi @awalch23,

Thanks again for you making such a detailed bug ticket. It really helped alot.  Please:

`git checkout buy-limit-feature`
`git pull`

I believe I fixed it. Let me know if the problem arises again and/or this fixes it.

Best,
Austin

**Comment by Orbitalz-eth** [comment]
Woohoo, can't wait to try it out!

**Comment by BatmanPDX** [comment]
ran into an error. The order went through but the time reset also executed. wonder if it went through right when the time was about to end. But this is what I got:

√ Calculating quantity...
√ Quantity Calculated: 4221
√ Purchasing... XVGBTC
√ Buy limit reset time reached.  Cancelling current order(s)
√ Cancelling current buy limit order...
√ Cancelled current buy limit order.
√ Resetting timer...
√ Timer reset.
√ Putting in new limit buy order at better price...
√ Calculating quantity...
√ Quantity Calculated: 4221
√ Purchasing... XVGBTC
√ Buy limit reset time reached.  Cancelling current order(s)
√ Cancelling current buy limit order...
| Queue: 2 Watchlist: 0(node:9632) UnhandledPromiseRejectionWarning: Error: UNKNOWN_ORDER
    at C:\wolf\node_modules\binance-api-node\dist\http.js:47:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:9632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
- Queue: 2 Watchlist: 0

**Comment by austinyearlykim** [comment]
going to close this ticket and focus attention on the other bug ticket that has the same issue! see you at https://github.com/austinyearlykim/wolf/issues/66 !

**Comment by awalch23** [comment]
Thanks! I'll give this a try when I get a chance.
