### ISSUE TITLE
Error: UNKNOWN_ORDER

### ISSUE THREAD

**Issue by tapir1** [austinyearlykim/wolf#69]
![bb4ba6158469fa46ce7ad8f78496092f](https://user-images.githubusercontent.com/35441718/42594242-9f22a86e-851c-11e8-9f1e-b98def1000ca.png)

EDIT: On top of this, the bot has also missed **many** selling opportunities that mathematically should've occurred. My phone alert would go off because the price hit PROFIT_PERCENTAGE, but upon checking the bot, it made no moves and continues searching.

Nevertheless, your effort is greatly appreciated!

**Comment by austinyearlykim** [comment]
Hi @tapir1!

To have WOLF execute more frequent trades try considering lowering your PROFIT_PERCENTAGE.  Wolf is pretty good at executing when it needs to; It would be really helpful if you gave specific numbers here so I can test them out!  

Thank you for reporting this!  I think I already know what might be happening.  I'll get to this sometime this weekend.

**Comment by austinyearlykim** [comment]
closing as there's not enough info to debug this as of yet, please resubmit a ticket with your .env config and a detailed scenario!

DONT POST YOUR BINANCE KEYS
DONT POST YOUR BINANCE KEYS
DONT POST YOUR BINANCE KEYS
DONT POST YOUR BINANCE KEYS
DONT POST YOUR BINANCE KEYS
DONT POST YOUR BINANCE KEYS
DONT POST YOUR BINANCE KEYS
DONT POST YOUR BINANCE KEYS
