### ISSUE TITLE
not enough balance in the account

### ISSUE THREAD

**Issue by pipinoloco** [austinyearlykim/wolf#7]
hello, i have like 1 ether in the account and when i choose for example TRXETH as pair when Wolf makes the test before running it says there is no enough balance in the account

**Comment by austinyearlykim** [comment]
hi @pipinoloco, can you post here your `.env`?   Make sure to not post your BINANCE_KEYS

I have a hunch that your ether is not "available" for trade, although you still have it in your wallet.  There is also the obvious case of your BUDGET being too high as well.

I'll be addressing this throughout today and tonight

**Comment by pipinoloco** [comment]
i have tested with big budget and small budget and always same mistake. I have tested with debian on a vps server, also on ubuntu, same mistake. i thought it could be a problem when compiling with node but after  
✓ should be able to ping Binance API (483ms)
    ✓ should be able to make signed requests (491ms)
    ✓ should be authorized to trade (379ms)
appears that mistake
{ AssertionError [ERR_ASSERTION]: not enough ETH balance in Binance wallet to use W.O.L.F with your budget
    at accountInfo.balances.forEach (/root/wolf/test/binance.js:53:25)
    at Array.forEach (<anonymous>)
    at /root/wolf/test/binance.js:50:38
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
    1) should have enough balance to afford budget

Validation & tests are successful!

  3 passing (3s)
  1 failing

  1) Binance
       should have enough balance to afford budget:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

**Comment by austinyearlykim** [comment]
Hi @pipinoloco can you pull down the latest changes? and run `npm test`

https://github.com/austinyearlykim/wolf/commit/7fb4d276c5dfb7d1a0ba80e3a91cb9d912bfde04

I added a little bit more logging to help with debugging, and cast strings to numbers in case something weird was happening via implicit coercion.

**Comment by pipinoloco** [comment]
solved, it helped when compared the balance in the config file with the balance on the script. thx

**Comment by austinyearlykim** [comment]
Awesome, thanks creating the issue @pipinoloco

**Comment by pitxels** [comment]
Hi I have a similar problem, I have this on my .env file:

```
BUDGET=0.01785347
PROFIT_PERCENTAGE=1.1
TARGET_ASSET=TRX
BASE_ASSET=BTC
```
And I am positive I have that BTC balance on Binance. When I run the test I get:
`not enough TRX balance in Binance wallet to use W.O.L.F with your budget.  Balance: 0.00000000 Budget: 0.01785347`

Why is it checking my TRX balance? when I am going to use BTC to buy It....
