### ISSUE TITLE
Timer reset bug

### ISSUE THREAD

**Issue by Orbitalz-eth** [austinyearlykim/wolf#71]
Ran into a problem with the timer reset.
When I ran the bot, the buy-limit went through. however, as I was waiting for the sell limit; this happended:

√ Calculating quantity...
√ Quantity Calculated: 218
√ Purchasing... TRXBTC
√ PURCHASED: 218.00000000 TRXBTC @ 0.00000477
√ Compounding...-0.00000477
√ Buy limit reset time reached. Cancelling current order(s)
√ Resetting timer...
√ Timer reset.
√ Putting in new limit buy order at better price...
√ Calculating quantity...
√ Quantity Calculated: 218
/ Queue: 0 Watchlist: 1PURCHASE ERROR: Error: Account has insufficient balance for requested action.
at C:\wolf\node_modules\binance-api-node\dist\http.js:47:13
at 
at process._tickCallback (internal/process/next_tick.js:188:7)
√ Cancelling 0 open orders created by W.O.L.F
√ Cancelled 0 opened orders created by W.O.L.F

Queue: 0 Watchlist: 1
It tried to put in a new order, even tho the previous order had already went through and was waiting for a sell limit. It seems that the timer doesn't cancel when a buy-limit goes through.

**Comment by austinyearlykim** [comment]
In lieu of recent discovery of a potential race condition I think it's best that I hold this feature off until the 4.0.0 release.  I will be closing this branch for now.  Please use ```master``` branch for all near-future bot activity!

Thanks all for being proactive.
