### ISSUE TITLE
Need Some Help To Start

### ISSUE THREAD

**Issue by LoayGhreep** [austinyearlykim/wolf#72]
Hello , i hope you well
Thanks for your effort
my issue is :
i Created file named ".env" in root directory ( As SU )
Even i Copied it into Wolf & Wolf/Modules
and filled this file with copy of template.env and added my parameters & Variables
it shows me this error
At npm start
![image](https://user-images.githubusercontent.com/42842021/44886147-fcd22c80-acc4-11e8-891c-7de78a513403.png)
At npm test
![image](https://user-images.githubusercontent.com/42842021/44886172-268b5380-acc5-11e8-870c-3f70fadf2edb.png)
i'm using VM
@austinyearlykim , I hope you help me with this :))
thanks in advanced ^^

**Comment by austinyearlykim** [comment]
Hi there!

You need to run `npm install` before running `npm start`!
