### ISSUE TITLE
Initializing...PURCHASE ERROR:  TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by duanebednorz** [austinyearlykim/wolf#77]
Hi,

This issue recently started popping up and I'm not sure how to correct it.
![indexOf issue](https://user-images.githubusercontent.com/35853003/58766326-cc186f80-8542-11e9-8da2-08ee6c957dc1.JPG)

**Comment by ghost** [comment]
Hello, I believe the correct is

![image](https://user-images.githubusercontent.com/53412000/62014097-bc945c00-b16a-11e9-9955-e5df88805f2f.png)

![image](https://user-images.githubusercontent.com/53412000/62014110-db92ee00-b16a-11e9-9ca9-b35d948ea01f.png)

**Comment by dynoalot** [comment]
I am having the same issue, but I am not understanding the solution you have posted. Can you please clarify?

**Comment by duanebednorz** [comment]
Thanks!
